/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: IsaacTheMaverick (https://sketchfab.com/IsaacTheMaverick)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/models/a6bf7976f3ac401e96907aa5b8a0c1c1
title: Low Poly Room
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei/useGLTF";

export default function Model(props) {
  const group = useRef();
  const { nodes, materials } = useGLTF("../../../scene.gltf");
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group
            position={[-126.86, 16.43, 29.04]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={[16.09, 16.09, 16.09]}
          >
            <mesh
              material={materials.UberTexture}
              geometry={nodes.Cube002_UberTexture_0.geometry}
            />
            <mesh
              material={materials.PC_Glass}
              geometry={nodes.Cube002_PC_Glass_0.geometry}
            />
            <mesh
              material={materials.Floor}
              geometry={nodes.Cube002_Floor_0.geometry}
            />
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("../../../scene.gltf");
